import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={montserrat.style} className='scrollbar-thin  scrollbar-thumb-blue-600 scrollbar-track-slate-500'>
        <div className="scrollbar-hide">
          {children}{" "}
          <script src="../path/to/flowbite/dist/flowbite.min.js" async></script>
        </div>
      </body>
    </html>
  );
}
